apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-ms-deployment
  namespace: user-service-ms-namespace
spec:
  selector:
    matchLabels:
      app: user-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: user-deployment
    spec:
      containers:
        - name: user-app-container
          image: abhishekvanaras/user-service-ms:2.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9195
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.default.svc.cluster.local:3306/ms-service?allowPublicKeyRetrieval=true&useSSL=false
            - name: DB_NAME
              value: ms-service
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: test1234
