apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-ms-deployment
  namespace: user-service-ms-namespace
spec:
  selector:
    matchLabels:
      app: user-deployment
  replicas: 4
  template:
    metadata:
      labels:
        app: user-deployment
    spec:
      containers:
        - name: user-app-container
          image: user-service-ms:1.0
          imagePullPolicy: IfNotPresent
          ports:
            --containerPort: 9195