apiVersion: v1
kind: Service
metadata:
  name: user-service-ms-service
  namespace: user-service-ms-namespace
spec:
  selector:
    app: user-deployment
  ports:
    - protocol: "TCP"
      port: 9195
      targetPort: 9195
  type: NodePort